### ISSUE TITLE
没有sql文件，没有前端源码

### ISSUE THREAD

**Issue by rzl** [Robinson28years/face-recognition-entrance-guard#1]
你好！ 我看了一下觉得项目挺好的，想部署在本地看一下，目前使用php7.1后端部署没有大问题，
但是发现以下问题，希望指导一下
1.项目中没有对应的数据库的初始内容
2.项目中的前端的代码，编译过的前端看不懂。

**Comment by Robinson28years** [comment]
抱歉，之前没看到这个issue
1.数据库初始迁移代码在database的migrations文件夹中，具体可以看下Laravel
2.前端仓库当时没放在一起而且锁上了，现在我把物业端前端代码public了，[物业管理端仓库](https://github.com/Robinson28years/face_property
)

tips:项目其实还涉及到python的人脸识别模块部分，还有swoole的websocket的部分。而且你应该还缺少客户端的树莓派部分代码。使用部署起来应该会比较麻烦，我目前只能提供给你一个思路

**Comment by rzl** [comment]
谢谢。
